# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-11 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screenshot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrbMatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('confidence', models.FloatField(default=0)),
                ('screenshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='screenshot.ScreenShot')),
            ],
        ),
    ]
