# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-11 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshot', '0002_orbmatcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbmatcher',
            name='status',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
