# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-11 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screenshot', '0003_auto_20161211_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ahash', models.CharField(max_length=100)),
                ('phash', models.CharField(max_length=100)),
                ('dhash', models.CharField(max_length=100)),
                ('whash', models.CharField(max_length=100)),
                ('screenshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='screenshot.ScreenShot')),
            ],
        ),
    ]
